### ISSUE TITLE
NEW detect user's locale for default option

### ISSUE THREAD

**Issue by muskie9** [dynamic/silverstripe-country-dropdown-field#1]

**Comment by lhasselb** [comment]
Hi,

first thank you developing this!

It seems switching from 
`config()->get('countries') `
to 
`getCountries() `
respects the user's locale.

Beside that it delivers a map containing both the locale code and name where the code is stored to the database and the name is displayed in the frontend.  

`    /**
     * @return array
     */
    protected function getDefaultCountriesList()
    {
        //return IntlLocales::singleton()->config()->get('countries');
        return IntlLocales::singleton()->getCountries();
    }
`

**Comment by muskie9** [comment]
Thanks for tracking that down @lhasselb. Are you comfortable submitting a PR for this?

**Comment by lhasselb** [comment]
Done. See https://github.com/dynamic/silverstripe-country-dropdown-field/pulls
