### ISSUE TITLE
Please tag this with a version number

### ISSUE THREAD

**Issue by silbinarywolf** [dynamic/silverstripe-country-dropdown-field#2]
@muskie9  Can you please tag this with a version number. Any version number?

**Comment by muskie9** [comment]
Hi @silbinarywolf, I've tagged [1.0.0](https://github.com/dynamic/silverstripe-country-dropdown-field/releases/tag/1.0.0) cheers!

**Comment by silbinarywolf** [comment]
@muskie9 Cheers!
