### ISSUE TITLE
Not for 4.1 and 4.2?

### ISSUE THREAD

**Issue by brasileric** [dynamic/silverstripe-country-dropdown-field#4]
Composer asks for ss4.0 only.

**Comment by muskie9** [comment]
Hi @brasileric, thanks for noting the constraint. Would you be willing to do a pull request updating the `recipe-cms` constraint to `"^1@dev || ^4@dev"`. That would resolve the version constraint issue.

**Comment by muskie9** [comment]
closed via #5 

A new release is available with this change [1.2.0](https://github.com/dynamic/silverstripe-country-dropdown-field/releases/tag/1.2.0)
