### ISSUE TITLE
Composer requirements calls for dev version, not stable

### ISSUE THREAD

**Issue by davejtoews** [dynamic/silverstripe-country-dropdown-field#7]
Line 28 from composer.json says the following:

```json
"silverstripe/recipe-cms": "^1@dev || ^4@dev"
```

~~The result is that on composer install, the latest dev commit recipe CMS which itself includes all the silverstripe core modules pulls in the latest dev version rather than a stable release on a clean install, or on a composer update.~~ Below is the output from a `composer outdated` in a project using this module.

![Screen Shot 2021-11-26 at 9 36 31 AM](https://user-images.githubusercontent.com/9664035/143610429-5a2fa025-4c56-4185-8cf1-dc7e826faffe.png)

**Comment by davejtoews** [comment]
Follow up: I was mistaken that this module was causing my issue. Keeping this ticket and the PR open though as it still makes sense to me not to be specifying dev versions in a stable module release.

**Comment by muskie9** [comment]
resolved via #8
